---
booktitle: Proceedings of the Fourteenth Symposium on Conformal and Probabilistic
  Prediction with Applications
shortname: COPA
publisher: PMLR
series: Proceedings of Machine Learning Research
year: '2025'
start: &1 2025-09-10
end: 2025-09-12
published: 2025-08-12
conference_number: '14'
volume: '266'
sections:
- name: Foundations and Generalisations of Conformal Prediction; Privacy, Robustness
    and Security; Multi-Output and Multi-Label Prediction; Conformal Regression and
    Predictive Distributions; Explainability and Decision Making; Applications; Online
    Testing, Change and Anomaly Detection; Extended Abstracts
  title: Foundations and Generalisations of Conformal Prediction; Privacy, Robustness
    and Security; Multi-Output and Multi-Label Prediction; Conformal Regression and
    Predictive Distributions; Explainability and Decision Making; Applications; Online
    Testing, Change and Anomaly Detection; Extended Abstracts
  published: 2025-08-12
layout: proceedings
issn: 2640-3498
id: COPA2025
month: 0
cycles: true
bibtex_editor: Nguyen, Khuong An and Luo, Zhiyuan and Papadopoulos, Harris and L"{o}fstr"{o}m,
  Tuwe and Carlsson, Lars and Bostr"{o}m, Henrik
editor:
- given: Khuong An
  family: Nguyen
- given: Zhiyuan
  family: Luo
- given: Harris
  family: Papadopoulos
- given: Tuwe
  family: L"ofstr"om
- given: Lars
  family: Carlsson
- given: Henrik
  family: Bostr"om
title: Proceedings of Machine Learning Research
description: |
  Proceedings of the Fourteenth Symposium on Conformal and Probabilistic Prediction with Applications
    Held in Royal Holloway, London, UK on 10-12 September 2025

  Published in 1 Sections as Volume 266 by the Proceedings of Machine Learning Research.
    Foundations and Generalisations of Conformal Prediction; Privacy, Robustness and Security; Multi-Output and Multi-Label Prediction; Conformal Regression and Predictive Distributions; Explainability and Decision Making; Applications; Online Testing, Change and Anomaly Detection; Extended Abstracts published on 12 August 2025

  Volume Edited by:
    Khuong An Nguyen
    Zhiyuan Luo
    Harris Papadopoulos
    Tuwe L"ofstr"om
    Lars Carlsson
    Henrik Bostr"om

  Series Editors:
    Neil D. Lawrence
date_str: 10--12 Sep
url: https://proceedings.mlr.press
author:
  name: PMLR
baseurl: "/v266"
twitter_username: MLResearchPress
github_username: mlresearch
markdown: kramdown
exclude:
- README.md
- Gemfile
- ".gitignore"
plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-remote-theme
remote_theme: mlresearch/jekyll-theme
style: pmlr
permalink: "/:title.html"
ghub:
  edit: true
  repository: v266
display:
  copy_button:
    bibtex: true
    endnote: true
    apa: true
  comments: false
volume_type: Volume
volume_dir: v266
email: ''
conference:
  name: Fourteenth Symposium on Conformal and Probabilistic Prediction with Applications
    (COPA 2025)
  url: https://copa-conference.com/
  location: Royal Holloway, London, UK
  dates:
  - *1
  - 2025-09-11
  - 2025-09-12
analytics:
  google:
    tracking_id: UA-92432422-1
link_visibility:
  openreview: true
  pdf: true
  supplementary: true
  software: true
  video: true
  arxiv: true
  doi: true
  website: true
orig_bibfile: copa2025_clean.bib
# Site settings
# Original source:  copa2025_clean.bib
